version: "3.8"

services:
  web:
    build: .
    container_name: django-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app   # OK para DEV/LAB; em produção remove
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=app.settings
    depends_on:
      - loki
    restart: unless-stopped
    networks:
      - network-postgres

  loki:
    image: grafana/loki:3.6.0
    container_name: loki
    ports:
      - 3100:3100
      - 7947:7946
      - 9095:9095
    command: -config.file=/mnt/config/loki-config.yaml
    volumes:
      - ./observability/loki/loki-config.yaml:/mnt/config/loki-config.yaml:ro
    restart: unless-stopped

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    ports:
      - "12345:12345" # UI + /-/reload
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./observability/alloy/config.alloy:/etc/alloy/config.alloy
      - alloy-data:/var/lib/alloy/data
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    depends_on:
      - loki
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.4.5
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=mailpit:1025
      - GF_SMTP_USER=
      - GF_SMTP_PASSWORD=
      - GF_SMTP_FROM_ADDRESS=grafana@local.test
      - GF_SMTP_FROM_NAME=Grafana
      - GF_SMTP_SKIP_VERIFY=true
      - GF_SMTP_STARTTLS_POLICY=NoStartTLS
    volumes:
      - grafana-data:/var/lib/grafana
      - ./observability/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - loki
    restart: unless-stopped

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
    #  - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    restart: unless-stopped
volumes:
  grafana-data:
    name: grafana-data
  alloy-data:
    name: alloy-data
networks:
  network-postgres:
    external: true