version: "3.8"

services:
  web:
    build: .
    container_name: django-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app   # OK para DEV/LAB; em produção remove
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=app.settings
    depends_on:
      - loki
    restart: unless-stopped

  loki:
    image: grafana/loki:3.6.0
    container_name: loki
    ports:
      - 3100:3100
      - 7947:7946
      - 9095:9095
    command: -config.file=/mnt/config/loki-config.yaml
    volumes:
      - ./observability/loki/loki-config.yaml:/mnt/config/loki-config.yaml:ro
    restart: unless-stopped

  # promtail:
  #   image: grafana/promtail:3.6.0
  #   container_name: promtail
  #   volumes:
  #     - /var/lib/docker/containers:/var/lib/docker/containers:ro
  #     - ./observability/promtail/promtail.yml:/mnt/config/promtail-config.yaml:ro
  #     - ./observability/promtail/log/:/var/log/:ro
  #   command: -config.file=/mnt/config/promtail-config.yaml
  #   depends_on:
  #     - loki
  #   restart: unless-stopped

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    ports:
      - "12345:12345" # UI + /-/reload
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./observability/alloy/config.alloy:/etc/alloy/config.alloy
      - alloy-data:/var/lib/alloy/data
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    depends_on:
      - loki
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.4.5
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./observability/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - loki
    restart: unless-stopped

volumes:
  grafana-data:
    name: grafana-data
  alloy-data:
    name: alloy-data
